version: '3.1'

services:

  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Fiap@2020
      MYSQL_DATABASE: fiapbank

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080